version: "3.9"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build: 
      dockerfile: Dockerfile
      context: "./api"
    #environment:
        #- UNSPLASH_SECRET_KEY=${UNSPLASH_SECRET_KEY}
  client:
    build:
      dockerfile: Dockerfile
      context: "./client"

networks:
  my-network:
    external: true
