name: Node.js CI

on:
  push:
    branches: ["**"]

jobs:
  staging:
    runs-on: self-hosted
    if: ${{ github.ref_name == 'develop' }}

     #env: 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run staging Docker container
        run: |
          docker-compose -f docker-compose.staging.yml -p my-staging-network up -d --build

  production:
    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' }}

     #env: 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and run production Docker container
        run: |
          docker-compose -f docker-compose.prod.yml -p my-production-network up -d --build

